export type IElement = {
  symbol: string;
  name: string;
  position: number;
  note?: string;
  answered?: boolean;
};

export const elements: Array<IElement> = [
  { symbol: "H", name: "Hydrogen", position: 1 },
  { symbol: "Li", name: "Lithium", position: 3 },
  { symbol: "Be", name: "Beryllium", position: 4 },
  { symbol: "Na", name: "Sodium", position: 11, note: "salt has no metal" },
  { symbol: "Mg", name: "Magnesium", position: 12 },
  { symbol: "K", name: "Potassium", position: 19 },
  { symbol: "Ca", name: "Calcium", position: 20 },
  { symbol: "Sc", name: "Scandium", position: 21 },
  { symbol: "Rb", name: "Rubidium", position: 37 },
  { symbol: "Sr", name: "Strontium", position: 38 },
  { symbol: "Y", name: "Yttrium", position: 39 },
  { symbol: "Cs", name: "Caesium", position: 55 },
  { symbol: "Ba", name: "Barium", position: 56 },
  { symbol: "La", name: "Lanthanum", position: 57 },
  { symbol: "Fr", name: "Francium", position: 87 },
  { symbol: "Ra", name: "Radium", position: 88 },
  { symbol: "Ac", name: "Actinium", position: 89 },
  { symbol: "Ti", name: "Titanium", position: 22 },
  { symbol: "Zr", name: "Zirconium", position: 40 },
  { symbol: "V", name: "Vanadium", position: 23 },
  { symbol: "Cr", name: "Chromium", position: 24 },
  { symbol: "Mn", name: "Manganese", position: 25 },
  { symbol: "Tc", name: "Technetium", position: 43 },
  { symbol: "Ru", name: "Ruthenium", position: 44 },
  { symbol: "Rh", name: "Rhodium", position: 45 },
  { symbol: "Pd", name: "Palladium", position: 46 },
  { symbol: "Ag", name: "Silver", position: 47 },
  { symbol: "Fe", name: "Iron", position: 26 },
  { symbol: "Co", name: "Cobalt", position: 27 },
  { symbol: "Ni", name: "Nickel", position: 28 },
  { symbol: "Cu", name: "Copper", position: 29 },
  { symbol: "Zn", name: "Zinc", position: 30 },
  { symbol: "Au", name: "Gold", position: 79 },
  { symbol: "Hg", name: "Mercury", position: 80, note: "Freddy Mercury" },
  { symbol: "Cd", name: "Cadmium", position: 48 },
  { symbol: "Br", name: "Bromine", position: 35 },
  { symbol: "Sn", name: "Tin", position: 50 },
  { symbol: "Sb", name: "Antimony", position: 51 },
  { symbol: "Te", name: "Tellurium", position: 52 },
  { symbol: "I", name: "Iodine", position: 53 },
  { symbol: "Tl", name: "Thallium", position: 81 },
  { symbol: "Pb", name: "Lead", position: 82 },
  { symbol: "Bi", name: "Bismuth", position: 83 },
  { symbol: "Po", name: "Polonium", position: 84 },
  { symbol: "B", name: "Boron", position: 5 },
  { symbol: "C", name: "Carbon", position: 6 },
  { symbol: "N", name: "Nitrogen", position: 7 },
  { symbol: "O", name: "Oxygen", position: 8 },
  { symbol: "F", name: "Fluorine", position: 9 },
  { symbol: "Al", name: "Aluminum", position: 13 },
  { symbol: "Si", name: "Silicon", position: 14 },
  { symbol: "P", name: "Phosphorus", position: 15 },
  { symbol: "S", name: "Sulfur", position: 16 },
  { symbol: "Cl", name: "Chlorine", position: 17 },
  { symbol: "Ga", name: "Gallium", position: 31 },
  { symbol: "Ge", name: "Germanium", position: 32 },
  { symbol: "As", name: "Arsenic", position: 33 },
  { symbol: "Se", name: "Selenium", position: 34 },
  { symbol: "He", name: "Helium", position: 2 },
  { symbol: "Ne", name: "Neon", position: 10 },
  { symbol: "Ar", name: "Argon", position: 18 },
  { symbol: "Kr", name: "Krypton", position: 36 },
  { symbol: "Xe", name: "Xenon", position: 54 },
  { symbol: "Rn", name: "Radon", position: 86 },
  { symbol: "W", name: "Tungsten", position: 74 },
  { symbol: "Nd", name: "Neodymium", position: 60 },
  { symbol: "U", name: "Uranium", position: 92 },
];
